import { User, Project, Skill } from '@/types'

export const MOCK_SKILLS: Skill[] = [
  { id: '1', name: 'Web Development', category: 'General', created_at: '2026-01-01' },
  { id: '2', name: 'Mobile Development', category: 'General', created_at: '2026-01-01' },
  { id: '3', name: 'AI / Machine Learning', category: 'General', created_at: '2026-01-01' },
  { id: '4', name: 'UI/UX', category: 'Design', created_at: '2026-01-01' },
  { id: '5', name: 'Cybersecurity', category: 'Security', created_at: '2026-01-01' },
  { id: '6', name: 'Data Science', category: 'Data', created_at: '2026-01-01' },
  { id: '7', name: 'Business', category: 'Business', created_at: '2026-01-01' },
  { id: '8', name: 'IoT', category: 'Hardware', created_at: '2026-01-01' },
  { id: '9', name: 'Python', category: 'Language', created_at: '2026-01-01' },
  { id: '10', name: 'React', category: 'Frontend', created_at: '2026-01-01' },
  { id: '11', name: 'TypeScript', category: 'Language', created_at: '2026-01-01' },
  { id: '12', name: 'Node.js', category: 'Backend', created_at: '2026-01-01' },
  { id: '13', name: 'Figma', category: 'Design', created_at: '2026-01-01' },
  { id: '14', name: 'SQL', category: 'Database', created_at: '2026-01-01' },
]

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    doer_id: '1',
    title: 'AI-Powered Study Assistant',
    description: 'A personalized learning tool that generates quizzes and summaries from lecture notes using natural language processing.',
    category: 'AI / MACHINE LEARNING',
    tags: ['Education / EdTech', 'Python', 'NLP', 'Machine Learning'],
    created_at: '2026-02-01',
    github_url: 'https://github.com',
    live_url: 'https://demo.com',
  },
  {
    id: 'p2',
    doer_id: '1',
    title: 'Smart Home Hub Firmware',
    description: 'Custom firmware for a centralized smart home controller, focusing on low latency and secure local network communication.',
    category: 'IOT',
    tags: ['Smart Home / IoT', 'C++', 'Embedded Systems'],
    created_at: '2026-02-05',
    github_url: 'https://github.com',
  },
  {
    id: 'p3',
    doer_id: '1',
    title: 'Algorithm Visualizer',
    description: 'Interactive web application built with React to help students visualize complex sorting and pathfinding algorithms.',
    category: 'WEB DEVELOPMENT',
    tags: ['Education / EdTech', 'React', 'JavaScript'],
    created_at: '2026-02-10',
    live_url: 'https://demo.com',
  },
  {
    id: 'p4',
    doer_id: '1',
    title: 'Student Budget Tracker',
    description: 'A cross-platform mobile app designed specifically for managing student finances, integrating with campus meal plans.',
    category: 'MOBILE DEVELOPMENT',
    tags: ['FinTech', 'React Native', 'Firebase'],
    created_at: '2026-02-12',
  },
  {
    id: 'p5',
    doer_id: '1',
    title: 'Campus Navigation System',
    description: 'Indoor routing application to help new students navigate complex university buildings using WiFi positioning.',
    category: 'MOBILE DEVELOPMENT',
    tags: ['Higher Education', 'Swift', 'WiFi Positioning'],
    created_at: '2026-02-14',
  },
  {
    id: 'p6',
    doer_id: '1',
    title: 'Data Analytics Dashboard',
    description: 'A comprehensive dashboard analyzing regional environmental data trends over the last decade using Python and D3.js.',
    category: 'DATA SCIENCE',
    tags: ['Environmental / Sustainability', 'Python', 'D3.js', 'Pandas'],
    created_at: '2026-02-15',
  }
]

export const MOCK_DOERS: (User & { skills: { name: string }[]; projectsCount?: number })[] = [
  {
    id: '1',
    email: 'alex.chen@university.edu',
    full_name: 'Alex Chen',
    username: 'alexchen',
    role: 'doer',
    status: 'approved',
    is_featured: true,
    created_at: '2026-01-15',
    program: 'Computer Science',
    year: 'Year 3',
    bio: 'Software engineering student interested in AI and developer tools. Beyond coursework, I actively participate in hackathons and open-source contributions.',
    portfolio_url: 'https://alexchen.dev',
    github_url: 'https://github.com/alexchen',
    linkedin_url: 'https://linkedin.com/in/alexchen',
    skills: [
      { name: 'Python' },
      { name: 'JavaScript' },
      { name: 'React' },
      { name: 'Machine Learning' },
      { name: 'Node.js' },
      { name: 'SQL' },
      { name: 'Git' },
      { name: 'Docker' }
    ],
    projectsCount: 6
  },
  {
    id: '2',
    email: 'jordan.lee@university.edu',
    full_name: 'Jordan Lee',
    username: 'jordanlee',
    role: 'doer',
    status: 'approved',
    is_featured: true,
    created_at: '2026-01-18',
    program: 'B.S. Computer Science',
    year: 'Senior',
    bio: 'Building accessible web experiences and modern full-stack architectures.',
    github_url: 'https://github.com',
    skills: [{ name: 'React' }, { name: 'TypeScript' }, { name: 'Node.js' }],
    projectsCount: 4
  },
  {
    id: '3',
    email: 'amara.okafor@university.edu',
    full_name: 'Amara Okafor',
    username: 'amaraokafor',
    role: 'doer',
    status: 'approved',
    is_featured: true,
    created_at: '2026-01-20',
    program: 'B.S. Data Science',
    year: 'Junior',
    bio: 'Turning raw data into clear insight, visualizations, and statistical models.',
    skills: [{ name: 'Python' }, { name: 'Pandas' }, { name: 'SQL' }],
    projectsCount: 3
  },
  {
    id: '4',
    email: 'ethan.kim@university.edu',
    full_name: 'Ethan Kim',
    username: 'ethankim',
    role: 'doer',
    status: 'approved',
    is_featured: true,
    created_at: '2026-01-22',
    program: 'B.A. UX Design',
    year: 'Senior',
    bio: 'Designing calm, usable interfaces backed by user research and iterative prototyping.',
    skills: [{ name: 'Figma' }, { name: 'Research' }, { name: 'Prototyping' }],
    projectsCount: 5
  },
  {
    id: '5',
    email: 'sofia.marino@university.edu',
    full_name: 'Sofia Marino',
    username: 'sofiamarino',
    role: 'doer',
    status: 'approved',
    is_featured: true,
    created_at: '2026-01-25',
    program: 'B.S. Cybersecurity',
    year: 'Sophomore',
    bio: 'Breaking things to make them safer. Penetration testing and network auditing.',
    skills: [{ name: 'Network Security' }, { name: 'Python' }, { name: 'Linux' }],
    projectsCount: 2
  },
  {
    id: '6',
    email: 'noah.bennett@university.edu',
    full_name: 'Noah Bennett',
    username: 'noahbennett',
    role: 'doer',
    status: 'approved',
    is_featured: false,
    created_at: '2026-01-26',
    program: 'B.S. Information Systems',
    year: 'Junior',
    bio: 'Connecting devices and data at scale through microcontrollers and distributed systems.',
    skills: [{ name: 'IoT' }, { name: 'C++' }, { name: 'Embedded Systems' }],
    projectsCount: 4
  },
  {
    id: '7',
    email: 'layla.haddad@university.edu',
    full_name: 'Layla Haddad',
    username: 'laylahaddad',
    role: 'doer',
    status: 'approved',
    is_featured: false,
    created_at: '2026-01-28',
    program: 'B.S. Business Analytics',
    year: 'Senior',
    bio: 'Bridging strategy and execution through data-driven decisions.',
    skills: [{ name: 'Strategy' }, { name: 'Excel' }, { name: 'Product' }],
    projectsCount: 3
  }
]
